### DISCUSSION TITLE
List of CSS class names

### DISCUSSION THREAD

**Discussion by pippim** [rouge-ruby/rouge#1881] [Q&A] [answered]
I'm enhancing my Github Pages website with dynamic selection of Rouge Highlighting Themes. I'm struggling with documenting the CSS class names. For example from your Monokai-Sublime code I see:

``` c
      style Comment::Multiline,
            Comment::Preproc,
            Comment::Single,
            Comment::Special,
            Comment,                          :fg => :dimgrey
```

So I know the first line is `.cm` and I know the last line is `.c` but this is by accident. In the CSS found I and modified a bit like Cayman Theme by adding bold and italics I see:

``` css
.highlight .cm { color: #5F9EA0; font-style: italic; } //
.highlight .cp { color: #5F9EA0; } //
.highlight .c1 { color: #5F9EA0; font-style: italic; } //
.highlight .cs { color: #5F9EA0; font-weight: bold; font-style: italic; } //
.highlight .c  { color: #5F9EA0; font-style: italic; } //
.highlight .ch { color: #5F9EA0; } // missing
.highlight .cd { color: #5F9EA0; font-style: italic; } //
.highlight .cpf{ color: #5F9EA0; } // missing
```

Is there code listing all the CSS class names and their description? EG

- <kbd>.c</kbd> = Comment
- <kbd>.cm</kbd> = Multi-line comment
- <kbd>.k</kbd> = Keyword, etc.

Also I notice Monokai-Sublime uses the class name `.ch` and `.cpf` which doesn't appear in Cayman Theme. What happens when a class name and color isn't provided?

Finally there is a Navy Blue color used in Monokai-Sublime that doesn't seem to be defined anywhere? It shows up when `text` formatting is used:

``` html
<div class="line_draw">
{% highlight text %}
{% include website_tree.txt %}
{% endhighlight %}
</div>
```

I did find a bit of a [legend](https://www.pippim.com/test.html#rouge-legend) which I put on my website. However I don't think it's very good and many CSS class names are missing.
