### ISSUE TITLE
New table lexer does not allow for selection of code

### ISSUE THREAD

**Issue by jneen** [rouge-ruby/rouge#1274]
I have suddenly remembered the reason we used the single-row table approach. While the new table lexer does allow for wrapping of lines, when a user attempts to select code, the line numbers become included in the selection. I'm not sure if there is a way around this, but I would like to look into it sometime in the near future.

**Comment by jneen** [comment]
cc @ashmaroli

**Comment by ashmaroli** [comment]
I believe this can be easily overcome by CSS:
```css
.rouge-line-table .rouge-gutter {
  -moz-user-select: none;
  -webkit-user-select: none;
  user-select: none;
}
```
