### ISSUE TITLE
The toml code block highlight is wrong

### ISSUE THREAD

**Issue by wsdjeg** [rouge-ruby/rouge#1417]
**Name of the lexer**
the toml code hight is wrong.

**Code sample**

put following code into markdow file, then generate the page.

```toml
[[layers]]
    name = 'lang#ring'
    ring_repl = 'D:\ringrepl\repl.ring'
```

**Screenshots**

![toml](https://user-images.githubusercontent.com/13142418/73362420-c5184b80-42e1-11ea-816d-c56648574073.png)

**Additional context**

**Literal strings** are surrounded by single quotes. Like basic strings, they must appear on a single line:

```toml
# What you see is what you get.
winpath  = 'C:\Users\nodejs\templates'
winpath2 = '\\ServerX\admin$\system32\'
quoted   = 'Tom "Dubs" Preston-Werner'
regex    = '<\i\c*\s*>'
```

there is no escaping in this string.
