### ISSUE TITLE
Avoid table styles unless needed

### ISSUE THREAD

**Issue by Arcovion** [rouge-ruby/rouge#142]
These lines:

``` css
.highlight table td { padding: 5px; }
.highlight table pre { margin: 0; }
```

Should only be added if `:line_numbers` are enabled
