### ISSUE TITLE
Error for Python TOML Pipfile with a Pinned Version

### ISSUE THREAD

**Issue by RamVasuthevan** [rouge-ruby/rouge#2069]
**Name of the lexer**
TOML

**Code sample**
Below is a simple Python TOML Pipfile with a pinned version 

```TOML
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "==2.25.1"
beautifulsoup4 = "*"

[dev-packages]

[requires]
python_version = "3.12"
```

The 2nd dot in the version of `requests` is marked as an [error](https://rouge.jneen.net/v4.3.0/toml/W1tzb3VyY2VdXQp1cmwgPSAiaHR0cHM6Ly9weXBpLm9yZy9zaW1wbGUiCnZlcmlmeV9zc2wgPSB0cnVlCm5hbWUgPSAicHlwaSIKCltwYWNrYWdlc10KcmVxdWVzdHMgPSAiPT0yLjI1LjEiCmJlYXV0aWZ1bHNvdXA0ID0gIioiCgpbZGV2LXBhY2thZ2VzXQoKW3JlcXVpcmVzXQpweXRob25fdmVyc2lvbiA9ICIzLjEyIgo). This the Pipfile generated by pipenv. I belive that it is valid TOML and that there should not be an error.
