### ISSUE TITLE
css `&` nesting selector support

### ISSUE THREAD

**Issue by juner** [rouge-ruby/rouge#2101]
**Name of the lexer**
*css*  `&` nesting selector support

**Code sample**

```css
body {
   &:has(span) {
      background-color: red;
   }
}
```

https://rouge.jneen.net/v4.5.1/css/Ym9keSB7CiAgICY6aGFzKHNwYW4pIHsKICAgICAgYmFja2dyb3VuZC1jb2xvcjogcmVkOwogICB9Cn0K

![image](https://github.com/user-attachments/assets/590332d9-5c41-468e-a72b-790fc4b6350a)

**Additional context**

https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector
