### ISSUE TITLE
TOML: Error when string contains an equals sign `=`

### ISSUE THREAD

**Issue by tyilo** [rouge-ruby/rouge#2107]
**Name of the lexer**
TOML

**Code sample**
A sample of the code that produces the bug.

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]
```
https://rouge.jneen.net/v4.5.1/toml/W3RhcmdldC54ODZfNjQtdW5rbm93bi1saW51eC1nbnVdCnJ1c3RmbGFncyA9IFsiLUN0YXJnZXQtY3B1PW5hdGl2ZSJdCg

[dingus]: http://rouge.jneen.net/
