### ISSUE TITLE
css media query support Range Context

### ISSUE THREAD

**Issue by juner** [rouge-ruby/rouge#2108]
**Name of the lexer**
css

**Code sample**

```css
@media (width > 100px) {
    :root {
        color: red;
    }
}
```

![Image](https://github.com/user-attachments/assets/4a0c24e5-a2fc-49fd-a039-cddbf67f6947)

https://rouge.jneen.net/v4.5.1/css/QG1lZGlhICh3aWR0aCA-IDEwMHB4KSB7CiAgICA6cm9vdCB7CiAgICAgICAgY29sb3I6IHJlZDsKICAgIH0KfQoK

**Additional context**

2.4.3. Evaluating Media Features in a Range Context - CSS Media Queries Level 4
https://www.w3.org/TR/mediaqueries-4/#mq-range-context

Media Queries: Range Syntax | Can I use... Support tables for HTML5, CSS3, etc
https://caniuse.com/css-media-range-syntax
