### ISSUE TITLE
CSS bug: unrecognized value for attribute "filter"

### ISSUE THREAD

**Issue by miparnisari** [rouge-ruby/rouge#914]
The following CSS code errors:

```css
.a-class {
     filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#4A8BA5',endColorstr='#30718B',GradientType=0);
}
```
